#!/usr/bin/env python3
"""Render the results tables from the committed CSVs.

The README used to carry these tables as hand-maintained markdown, and they
drifted from the data they claimed to summarise: the published strategy p50 of
"~0 ns" sat beside a summary.csv that said 399 ns, roughly a 30x difference, in
the same commit.

This script is the fix. It reads reports/data/*.csv and writes
reports/tables.md with a do-not-edit header, so the tables are generated from
the artifacts rather than transcribed from them. The README includes the
rendered file by reference. Running it is part of scripts/measure.sh.

Usage:  python3 tools/render_tables.py
"""
from __future__ import annotations

import csv
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
DATA = REPO / "reports" / "data"
OUT = REPO / "reports" / "tables.md"


def read_csv(name: str) -> list[dict[str, str]]:
    path = DATA / name
    if not path.exists():
        return []
    with path.open(newline="") as fh:
        return list(csv.DictReader(fh))


def read_meta(name: str) -> dict:
    path = DATA / f"{name}.meta.json"
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError:
        return {}


def provenance(name: str) -> str:
    m = read_meta(name)
    if not m:
        return (
            f"> No provenance recorded for `{name}`. "
            "Regenerate with `scripts/measure.sh` to produce one.\n"
        )
    machine = m.get("machine", {})
    return (
        f"> Source: `{name}` — generated by `{m.get('command', '?')}`\n"
        f"> at commit `{m.get('git_commit', '?')}` on {m.get('generated_utc', '?')}.\n"
        f"> Machine: {machine.get('cpu', '?')}, {machine.get('logical_cores', '?')} logical cores, "
        f"{machine.get('os', '?')}.\n"
    )


def fmt_stage(s: str) -> str:
    return {
        "feed": "feed handler (recv → enqueue)",
        "strategy": "strategy (dequeue → decision)",
        "gateway": "gateway (dequeue → wire-ready)",
        "end_to_end": "**end-to-end (arrival → order on wire)**",
        "round_trip": "round trip (arrival → fill received)",
    }.get(s, s)


def latency_table() -> str:
    rows = read_csv("summary.csv")
    if not rows:
        return "_No summary.csv. Run `scripts/measure.sh`._\n"

    res = rows[0].get("resolution_ns", "?")
    src = rows[0].get("clock_source", "?")

    out = [
        "### End-to-end latency",
        "",
        "| stage | n | p50 | p90 | p99 | p99.9 | max | mean |",
        "|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for r in rows:
        out.append(
            "| {} | {} | {} | {} | {} | {} | {} | {} |".format(
                fmt_stage(r["stage"]), r["n"], r["p50"], r["p90"],
                r["p99"], r["p999"], r["max"], r["mean"],
            )
        )
    out += [
        "",
        f"All figures in nanoseconds. Clock source `{src}`, tick period {res} ns.",
        "",
        "A cell reading `<N` means the span finished inside the clock's resolution "
        "floor and cannot be quantified further. It does not mean zero: it means "
        "the measurement stops there. Percentiles are HdrHistogram bucket upper "
        "bounds, so they may exceed the largest single observation.",
        "",
        provenance("summary.csv"),
    ]
    return "\n".join(out)


def components_table() -> str:
    rows = read_csv("components.csv")
    if not rows:
        return "_No components.csv. Run `scripts/measure.sh`._\n"

    reps = rows[0].get("reps", "?")
    iters = rows[0].get("iters_per_rep", "?")
    baseline = rows[0].get("baseline_ns")

    out = [
        "### Hot-path component costs",
        "",
        "| component | median ns/op | p25 | p75 | M ops/s |",
        "|---|---:|---:|---:|---:|",
    ]
    for r in rows:
        out.append(
            "| `{}` | {} | {} | {} | {} |".format(
                r["component"], r["ns_per_op"], r.get("ns_p25", "—"),
                r.get("ns_p75", "—"), r["mops"],
            )
        )
    out += [
        "",
        f"Median and inter-quartile range across {reps} repetitions of {iters} "
        "iterations each, after discarding a warm-up repetition. Every measured "
        "value is held live with an inline-asm optimisation barrier, so the "
        "computation is not deleted as dead code.",
        "",
    ]
    if baseline:
        out += [
            f"`tsc_now` is an upper bound, not an isolated cost. An empty "
            f"barrier-only loop runs at {baseline} ns/iteration, which is within "
            "noise of the counter-read loop itself: the read issues alongside the "
            "loop's own work rather than serialising with it, so the two are not "
            "separable in throughput mode.",
            "",
        ]
    out.append(provenance("components.csv"))
    return "\n".join(out)


def false_sharing_table() -> str:
    rows = read_csv("false_sharing.csv")
    if not rows:
        return "_No false_sharing.csv. Run `scripts/measure.sh`._\n"

    out = [
        "### Cache-line padding A/B",
        "",
        "| queue layout | M ops/s |",
        "|---|---:|",
    ]
    by_name = {}
    for r in rows:
        out.append("| {} | {} |".format(r["variant"], r["mops"]))
        try:
            by_name[r["variant"]] = float(r["mops"])
        except (TypeError, ValueError):
            pass

    line = rows[0].get("cache_line_bytes", "?")
    threads = rows[0].get("hardware_threads", "?")
    pinned = rows[0].get("pinned", "?")
    out.append("")

    padded = next((v for k, v in by_name.items() if k.startswith("padded")), None)
    unpadded = next((v for k, v in by_name.items() if k.startswith("unpadded")), None)
    if padded and unpadded:
        ratio = padded / unpadded
        faster = "unpadded" if ratio < 1 else "padded"
        out.append(
            f"On this machine the **{faster}** layout is "
            f"{max(ratio, 1/ratio):.2f}x faster. The two queues are identical "
            "apart from the `alignas` on the cursors — including the cached "
            "opposite-cursor snapshots, without which the comparison measures "
            "two differences at once."
        )
        out.append("")
    out += [
        f"Measured with a {line}-byte cache line on a machine with {threads} "
        f"hardware threads, pinning: {pinned}. This result is a property of a "
        "cache topology, not of the code, and it is measured on AArch64 only. "
        "It should not be generalised to x86 without an x86 run.",
        "",
        provenance("false_sharing.csv"),
    ]
    return "\n".join(out)


def main() -> int:
    if not DATA.exists():
        print(f"error: {DATA} does not exist; run scripts/measure.sh", file=sys.stderr)
        return 1

    # Deliberately no render timestamp. This file is checked into git and CI
    # re-renders it to prove it has not drifted from the CSVs; a wall-clock
    # stamp would make that check fail on every run and teach everyone to
    # ignore it. The real timestamps live in the per-artifact provenance
    # blocks below, which change only when the data does.
    body = [
        "<!-- GENERATED FILE - DO NOT EDIT BY HAND.",
        "     Produced by tools/render_tables.py from reports/data/*.csv.",
        "     Edit the measurement, not this file. -->",
        "",
        "## Results",
        "",
        latency_table(),
        "",
        components_table(),
        "",
        false_sharing_table(),
    ]
    OUT.write_text("\n".join(body) + "\n")
    print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
